sudo: false
cache: bundler
bundler_args: --without development

before_install:
  - gem install bundler -v '> 1.5.0'

rvm:
  - 2.2.4

script: bundle exec rake

branches:
  only:
    - master

services:
  - mongodb
